import { StyleSheet } from 'react-native';

export const BG = '#CDAA6D';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: BG,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingBottom: 32,
  },
  label: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.85)',
    marginBottom: 8,
    marginTop: 16,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: '#1e293b',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  saveBtn: {
    marginTop: 20,
    backgroundColor: '#F28537',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  saveBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#fff',
    marginTop: 22,
    marginBottom: 10,
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.35)',
    marginBottom: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.15)',
  },
  rowText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
    marginRight: 12,
  },
  rowSub: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.65)',
    marginTop: 4,
  },
  removeBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(185,28,28,0.25)',
  },
  removeBtnText: {
    color: '#fecaca',
    fontSize: 13,
    fontWeight: '700',
  },
  empty: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.6)',
    fontStyle: 'italic',
    paddingVertical: 8,
  },
  fieldHint: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.65)',
    marginBottom: 10,
    lineHeight: 17,
  },
  imagemPreviewWrap: {
    height: 160,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#fff',
    marginBottom: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  imagemPreview: {
    width: '100%',
    height: '100%',
  },
  imagemPlaceholder: {
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
    paddingHorizontal: 24,
  },
  imagemActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    marginBottom: 8,
  },
  imagemBtn: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: '#fff',
    marginRight: 10,
    marginBottom: 8,
  },
  imagemBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#334155',
  },
  imagemBtnDanger: {
    backgroundColor: 'rgba(254,242,242,0.95)',
  },
  imagemBtnDangerText: {
    color: '#b91c1c',
  },
  saveFotoBtn: {
    marginTop: 8,
    backgroundColor: '#F28537',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  saveFotoBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
  },
  removeDestaqueBtn: {
    marginTop: 14,
    alignSelf: 'flex-start',
    paddingVertical: 8,
  },
  removeDestaqueText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fecaca',
  },
  liderancaLink: {
    alignSelf: 'flex-start',
    marginTop: 6,
    marginBottom: 8,
    paddingVertical: 6,
  },
  liderancaLinkText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
    textDecorationLine: 'underline',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#3d3528',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 18,
    paddingTop: 18,
    maxHeight: '85%',
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#fff',
    marginBottom: 12,
  },
  modalHint: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.65)',
    marginBottom: 10,
    lineHeight: 16,
  },
  modalSection: {
    marginBottom: 14,
  },
  modalSectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.85)',
    marginBottom: 8,
    textTransform: 'uppercase',
  },
  modalOption: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginBottom: 6,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  modalOptionOn: {
    backgroundColor: 'rgba(255,255,255,0.2)',
  },
  modalOptionText: {
    fontSize: 15,
    color: '#fff',
    fontWeight: '600',
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 8,
  },
  modalBtnPad: {
    marginLeft: 8,
  },
  liderancaBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#fff',
    textDecorationLine: 'underline',
  },
});
