import { StyleSheet } from 'react-native';

export const BG = '#CDAA6D';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: BG,
  },
  loadingWrap: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  kav: {
    flex: 1,
    width: '100%',
  },
  scroll: {
    flexGrow: 1,
    alignItems: 'stretch',
    width: '100%',
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 36,
  },
  inner: {
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
  },
  logoSpacer: {
    marginBottom: 8,
  },
  title: {
    fontSize: 17,
    fontWeight: '800',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 4,
    letterSpacing: 1,
    paddingHorizontal: 8,
  },
  subtitle: {
    fontSize: 15,
    color: 'rgba(255,255,255,0.92)',
    textAlign: 'center',
    marginTop: 4,
    marginBottom: 20,
    fontWeight: '500',
    paddingHorizontal: 8,
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.95)',
    textAlign: 'center',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 12,
    marginTop: 6,
  },
  fotoSection: {
    marginBottom: 18,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 12,
    padding: 16,
  },
  fotoRow: {
    alignItems: 'center',
  },
  fotoPreview: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: 'rgba(255,255,255,0.45)',
    marginBottom: 12,
    borderWidth: 3,
    borderColor: 'rgba(255,255,255,0.55)',
  },
  fotoActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fotoBtn: {
    marginHorizontal: 6,
    marginBottom: 8,
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 10,
    backgroundColor: '#F28537',
  },
  fotoBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
  fotoBtnOutline: {
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.85)',
    backgroundColor: 'transparent',
  },
  fotoBtnMutedText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
  permissaoBox: {
    marginBottom: 18,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 12,
    padding: 14,
  },
  permissaoLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.85)',
    marginBottom: 6,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  permissaoValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    textTransform: 'capitalize',
  },
  hint: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.72)',
    marginBottom: 14,
    lineHeight: 16,
    textAlign: 'center',
    paddingHorizontal: 4,
  },
  errorRoot: {
    color: '#7f1d1d',
    fontSize: 14,
    marginBottom: 14,
    textAlign: 'center',
    fontWeight: '600',
    backgroundColor: 'rgba(255,255,255,0.35)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    overflow: 'hidden',
  },
  btnWrap: {
    marginTop: 12,
    width: '100%',
    marginBottom: 8,
  },
});
