import { StyleSheet } from 'react-native';

export const BG = '#CDAA6D';
export const HEADER_BG = '#B89550';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: BG,
  },
  screenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: HEADER_BG,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.06)',
  },
  menuBtn: {
    padding: 10,
    marginLeft: -6,
  },
  menuBar: {
    width: 22,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#fff',
    marginBottom: 5,
  },
  menuBarLast: {
    marginBottom: 0,
  },
  headerTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '800',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: 0.3,
    paddingHorizontal: 8,
  },
  headerLogo: {
    width: 44,
    height: 36,
    marginRight: -4,
  },
  scrollFlex: {
    flex: 1,
  },
  emptyScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingVertical: 24,
    paddingBottom: 100,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    marginBottom: 10,
  },
  emptyText: {
    fontSize: 15,
    color: 'rgba(255,255,255,0.88)',
    textAlign: 'center',
    marginBottom: 8,
    lineHeight: 22,
  },
  emptyHint: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.72)',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 19,
    paddingHorizontal: 8,
  },
  listFlex: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 100,
  },
  columnWrap: {
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 14,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
  },
  cardImageWrap: {
    height: 148,
    backgroundColor: '#e8e8e8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardImage: {
    width: '100%',
    height: '100%',
  },
  placeholderInner: {
    opacity: 0.45,
  },
  placeholderRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  placeholderMountain: {
    width: 0,
    height: 0,
    borderLeftWidth: 22,
    borderRightWidth: 22,
    borderBottomWidth: 28,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#b4b4b4',
  },
  placeholderSun: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#d4d4d4',
    marginBottom: 6,
    marginRight: 6,
  },
  cardBody: {
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  cardNome: {
    fontSize: 16,
    fontWeight: '800',
    color: '#c53030',
    marginBottom: 6,
  },
  cardLocal: {
    fontSize: 14,
    fontWeight: '700',
    color: '#334155',
    marginBottom: 4,
  },
  cardEndereco: {
    fontSize: 13,
    fontWeight: '500',
    color: '#475569',
    lineHeight: 19,
    marginBottom: 6,
  },
  cardMeta: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
    marginBottom: 10,
  },
  mapsBtn: {
    marginHorizontal: 12,
    marginBottom: 12,
    paddingVertical: 11,
    borderRadius: 10,
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#F28537',
    alignItems: 'center',
  },
  mapsBtnText: {
    fontSize: 14,
    fontWeight: '800',
    color: '#F28537',
    letterSpacing: 0.3,
  },
  fab: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: '#F28537',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    zIndex: 20,
  },
  fabPlus: {
    color: '#fff',
    fontSize: 34,
    fontWeight: '300',
    marginTop: -2,
    lineHeight: 38,
  },
});
