import { StyleSheet } from 'react-native';

export const BG = '#CDAA6D';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: BG,
  },
  kav: {
    flex: 1,
    width: '100%',
  },
  scroll: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 36,
  },
  inner: {
    width: '100%',
    maxWidth: 440,
    alignSelf: 'center',
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.95)',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 8,
    marginTop: 4,
  },
  dateTouchable: {
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  dateTouchableText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1e293b',
  },
  dateTouchableHint: {
    fontSize: 12,
    color: '#64748b',
    marginTop: 6,
  },
  dateModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  dateModalCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    overflow: 'hidden',
    paddingTop: 8,
  },
  dateModalDone: {
    alignSelf: 'stretch',
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: '#F28537',
  },
  dateModalDoneText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 16,
  },
  multiselectCard: {
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.08)',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.9)',
    textAlign: 'center',
    marginBottom: 20,
    fontWeight: '500',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 14,
    marginBottom: 8,
  },
  sectionHeaderRowSpaced: {
    marginTop: 20,
  },
  sectionTitleLeft: {
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.98)',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginRight: 12,
  },
  sectionLink: {
    fontSize: 13,
    fontWeight: '700',
    color: '#fff',
    textDecorationLine: 'underline',
  },
  sectionLinkDisabled: {
    color: 'rgba(255,255,255,0.35)',
  },
  emptyInline: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.65)',
    fontStyle: 'italic',
    marginBottom: 10,
    textAlign: 'center',
  },
  listCard: {
    borderRadius: 10,
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.12)',
    marginBottom: 6,
  },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.12)',
  },
  listRowText: {
    flex: 1,
    marginRight: 10,
  },
  listRowNome: {
    fontSize: 15,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.95)',
  },
  listRowSub: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.7)',
    marginTop: 2,
  },
  listRowObs: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.55)',
    marginTop: 6,
    fontStyle: 'italic',
    lineHeight: 17,
  },
  removeLink: {
    fontSize: 13,
    fontWeight: '700',
    color: 'rgba(255,200,200,0.95)',
  },
  chipsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  chip: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 20,
    maxWidth: '100%',
    marginRight: 8,
    marginBottom: 8,
  },
  chipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
  sheetOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  sheetAvoid: {
    width: '100%',
  },
  sheetCard: {
    backgroundColor: '#3d3528',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  sheetCardTall: {
    backgroundColor: '#3d3528',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 16,
    paddingTop: 18,
    maxHeight: '72%',
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
    marginBottom: 6,
  },
  sheetHint: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.65)',
    marginBottom: 14,
    lineHeight: 16,
  },
  sheetFieldLabelSpaced: {
    marginTop: 12,
  },
  sheetSub: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.7)',
    marginBottom: 12,
  },
  sheetActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 16,
  },
  sheetBtnPrimary: {
    backgroundColor: '#F28537',
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: 10,
  },
  sheetBtnPrimaryText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 15,
  },
  sheetBtnSecondary: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
    marginRight: 8,
  },
  sheetBtnSecondaryText: {
    color: 'rgba(255,255,255,0.85)',
    fontWeight: '700',
    fontSize: 15,
  },
  membrosFlatList: {
    maxHeight: 280,
  },
  membroSelectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.12)',
    borderRadius: 8,
    marginBottom: 4,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  membroSelectRowOn: {
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  membroSelectCheck: {
    fontSize: 18,
    color: '#fff',
    marginRight: 12,
    width: 28,
  },
  membroSelectNome: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
  },
  hint: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.72)',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 16,
  },
  errorRoot: {
    color: '#7f1d1d',
    fontSize: 14,
    marginBottom: 14,
    textAlign: 'center',
    fontWeight: '600',
    backgroundColor: 'rgba(255,255,255,0.35)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    overflow: 'hidden',
  },
  btnWrap: {
    marginTop: 12,
    width: '100%',
  },
  presencaHint: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.72)',
    textAlign: 'center',
    marginBottom: 12,
    lineHeight: 16,
    paddingHorizontal: 4,
  },
  semMembros: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.8)',
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 12,
    lineHeight: 20,
    paddingHorizontal: 8,
  },
  errorField: {
    fontSize: 12,
    color: '#7f1d1d',
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
});
