import { StyleSheet } from 'react-native';

export const BG = '#CDAA6D';
export const HEADER_BG = '#B89550';

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: BG,
  },
  screenHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: HEADER_BG,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.06)',
  },
  menuBtn: {
    padding: 10,
    marginLeft: -6,
  },
  menuBar: {
    width: 22,
    height: 3,
    borderRadius: 2,
    backgroundColor: '#fff',
    marginBottom: 5,
  },
  menuBarLast: {
    marginBottom: 0,
  },
  headerTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '800',
    color: '#fff',
    textAlign: 'center',
    letterSpacing: 0.3,
    paddingHorizontal: 8,
  },
  headerLogo: {
    width: 44,
    height: 36,
    marginRight: -4,
  },
  scrollFlex: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
    paddingTop: 12,
  },
  intro: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.88)',
    marginBottom: 16,
    lineHeight: 20,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.9)',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  selectTouchable: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  selectValue: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#1e293b',
    marginRight: 8,
  },
  selectChevron: {
    fontSize: 12,
    color: '#64748b',
  },
  periodRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  periodHalf: {
    flex: 1,
  },
  periodHalfRight: {
    marginLeft: 12,
  },
  dateChip: {
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  dateChipText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1e293b',
    textAlign: 'center',
  },
  chartCard: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  chartTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#fff',
    marginBottom: 4,
    textAlign: 'center',
  },
  chartSub: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.75)',
    textAlign: 'center',
    marginBottom: 8,
  },
  chartStats: {
    marginTop: 8,
    alignSelf: 'stretch',
    gap: 8,
  },
  chartStatLine: {
    fontSize: 13,
    lineHeight: 20,
    color: '#fff',
  },
  chartStatLabel: {
    fontWeight: '600',
    color: 'rgba(255,255,255,0.9)',
  },
  chartStatValue: {
    fontWeight: '800',
    color: '#fff',
  },
  chartHint: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.65)',
    lineHeight: 16,
    marginTop: 10,
    textAlign: 'center',
  },
  linkBtn: {
    backgroundColor: '#F28537',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 24,
  },
  linkBtnText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 15,
    textAlign: 'center',
    paddingHorizontal: 8,
  },
  linkBtnDisabled: {
    opacity: 0.55,
  },
  pdfOutlineBtn: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: 2,
    borderColor: '#F28537',
  },
  pdfOutlineBtnText: {
    color: '#c2410c',
    fontWeight: '800',
    fontSize: 15,
    textAlign: 'center',
    paddingHorizontal: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  modalCard: {
    backgroundColor: '#3d3528',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingHorizontal: 16,
    paddingTop: 18,
    maxHeight: '70%',
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#fff',
    marginBottom: 12,
  },
  modalList: {
    maxHeight: 360,
  },
  modalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.12)',
    borderRadius: 8,
    marginBottom: 6,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  modalRowOn: {
    backgroundColor: 'rgba(255,255,255,0.14)',
  },
  modalRowText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
    marginRight: 12,
  },
  modalCheck: {
    fontSize: 16,
    color: '#86efac',
    fontWeight: '800',
  },
  dateModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  dateModalCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    overflow: 'hidden',
    paddingTop: 8,
  },
  dateModalDone: {
    alignSelf: 'stretch',
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: '#F28537',
  },
  dateModalDoneText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 16,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.12)',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  nome: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
    marginRight: 12,
  },
  meta: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.75)',
    marginTop: 4,
  },
  chevron: {
    fontSize: 18,
    color: 'rgba(255,255,255,0.85)',
    fontWeight: '600',
  },
  empty: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.65)',
    fontStyle: 'italic',
    textAlign: 'center',
    marginTop: 32,
    paddingHorizontal: 16,
  },
});
